### ISSUE TITLE
UnwrapBinaryMessage return EOF error when biz resp is nil

### ISSUE THREAD

**Issue by wodeqiangne** [cloudwego/dynamicgo#69]
**Describe the bug**

thrift.UnwrapBinaryMessage could not unwrap empty biz buf

**To Reproduce**

```
func TestBinaryUnwrap(t *testing.T) {
	b := BinaryProtocol{
		Buf:  nil,
		Read: 0,
	}
	var i32 int32 = -2147418110
	b.WriteI32(i32)
	b.WriteString("DummyNew")
	b.WriteI32(1)
	b.WriteByte(byte(STOP))
	_, _, _, _, _, err := UnwrapBinaryMessage(b.Buf)

	t.Errorf("UnwrapBinaryMessage() error = %v", err)

}
```

run the test case

**Expected behavior**

err is nil and body is empty slice bytes

**Screenshots**

**Version:**

v0.3.0

**Environment:**

**Additional context**

**Comment by AsterDY** [comment]
`UnwrapBinaryMessage` is used to decode Standard Thrift Message, INCLUDING `method args struct` (=== MethodX(1: reqX)`, Please check and understand thrift specification first
