### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by flyerxp** [cloudwego/dynamicgo#74]
**编译报错**

**To Reproduce**

1. 在kitex rpc项目里使用这个0.4.0的库
2. go build -o output/bin/${RUN_NAME} '...'

**报错信息**
go: downloading github.com/flyerxp/webrpclib/v2 v2.0.5
go: downloading github.com/cloudwego/thriftgo v0.3.17
go: downloading github.com/aliyun/alibaba-cloud-sdk-go v1.63.13
# github.com/cloudwego/kitex/pkg/generic/thrift
/root/go/pkg/mod/github.com/cloudwego/kitex@v0.10.3/pkg/generic/thrift/http_go116plus_amd64.go:69:67: field.Type().Type().ToThriftTType undefined (type "github.com/cloudwego/dynamicgo/thrift".Type has no field or method ToThriftTType)
/root/go/pkg/mod/github.com/cloudwego/kitex@v0.10.3/pkg/generic/thrift/json_go116plus_amd64.go:105:67: field.Type().Type().ToThriftTType undefined (type "github.com/cloudwego/dynamicgo/thrift".Type has no field or method ToThriftTType)

**Version:**
go.mod 配置
github.com/cloudwego/kitex v0.10.3
github.com/cloudwego/dynamicgo v0.4.0 // indirect

**Environment:**

The output of `go env`.

**
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY='github.com/flyerxp/shopping.shop,github.com/flyerxp/shopping.shop,github.com/flyerxp/web.www,github.com/flyerxp/globalStruct,github.com/flyerxp/content.news.rpc,github.com/flyerxp/shopping.shop.rpc,github.com/flyerxp/shopping.report,github.com/flyerxp/shopping.pay.rpc'
GONOSUMDB='github.com/flyerxp/shopping.shop,github.com/flyerxp/shopping.shop,github.com/flyerxp/web.www,github.com/flyerxp/globalStruct,github.com/flyerxp/content.news.rpc,github.com/flyerxp/shopping.shop.rpc,github.com/flyerxp/shopping.report,github.com/flyerxp/shopping.pay.rpc'
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE='github.com/flyerxp/shopping.shop,github.com/flyerxp/shopping.shop,github.com/flyerxp/web.www,github.com/flyerxp/globalStruct,github.com/flyerxp/content.news.rpc,github.com/flyerxp/shopping.shop.rpc,github.com/flyerxp/shopping.report,github.com/flyerxp/shopping.pay.rpc'
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/www/site/code/shop/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3744700916=/tmp/go-build -gno-record-gcc-switches'
**

**Comment by AsterDY** [comment]
downgrade to v0.3.0

**Comment by AsterDY** [comment]
DO NOT ALWAYS `go get -u`
